'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ImagePlus,RefreshCw,Camera as CameraIcon,ArrowLeft} from 'lucide-react';
import {resizePhoto} from '@/lib/explode/client';
export default function Camera({onCapture,onBack,onNew,canGoBack}:{onCapture:(image:string)=>void;onBack:()=>void;onNew:()=>void;canGoBack:boolean}){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),file=useRef<HTMLInputElement>(null),run=useRef(0);const[ready,setReady]=useState(false),[status,setStatus]=useState(''),[facing,setFacing]=useState<'environment'|'user'>('environment'),[busy,setBusy]=useState(false);
 const stop=useCallback(()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setReady(false)},[]);
 const start=useCallback(async()=>{const n=++run.current;stop();setStatus('Opening camera…');try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera unavailable');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1440}},audio:false});if(n!==run.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play();if(n===run.current){setReady(true);setStatus('')}}}catch(e){if(n===run.current)setStatus(e instanceof DOMException&&e.name==='NotAllowedError'?'Allow camera access, or choose a photo.':'Choose a photo, or try the camera again.')}},[facing,stop]);
 useEffect(()=>{void start();const visibility=()=>{if(document.hidden){run.current++;stop()}else void start()};document.addEventListener('visibilitychange',visibility);return()=>{run.current++;stream.current?.getTracks().forEach(t=>t.stop());document.removeEventListener('visibilitychange',visibility)}},[start,stop]);
 const accept=async(src:string)=>{setBusy(true);try{const image=await resizePhoto(src);run.current++;stop();onCapture(image)}catch(e){setStatus((e as Error).message);setBusy(false)}};
 const snap=()=>{if(!video.current?.videoWidth)return;const v=video.current,c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d')!.drawImage(v,0,0);void accept(c.toDataURL('image/jpeg',.94))};
 const upload=(f?:File)=>{if(!f)return;if(!f.type.startsWith('image/')||f.size>24_000_000){setStatus('Choose an image smaller than 24 MB.');return}const reader=new FileReader();reader.onload=()=>void accept(String(reader.result));reader.onerror=()=>setStatus('That photo could not be opened.');reader.readAsDataURL(f)};
 return <section className={'camera-screen '+(!ready?'camera-waiting':'')}><video ref={video} autoPlay playsInline muted className={facing==='user'?'mirrored':''}/><header className="camera-header">{canGoBack?<button className="camera-round" onClick={onBack} aria-label="Back to object"><ArrowLeft size={20}/></button>:<span className="camera-header-spacer"/>}<button className="wordmark" onClick={()=>{onNew();void start()}} aria-label="Take a new photo">explode me<span>✳</span></button><button className="camera-round" onClick={()=>setFacing(f=>f==='environment'?'user':'environment')} aria-label="Switch camera"><RefreshCw size={20}/></button></header>{!ready&&<div className="camera-invitation"><div className="aperture-mark" aria-hidden><span/><span/><span/></div><h1>What’s inside?</h1><p role="status">{status}</p><button className="primary-button" onClick={()=>void start()} disabled={busy}><CameraIcon size={18}/>Open camera</button><button className="text-button" onClick={()=>file.current?.click()} disabled={busy}>Choose a photo</button></div>}<input type="file" accept="image/*" hidden ref={file} onChange={e=>upload(e.target.files?.[0])}/>{ready&&<div className="capture-bar"><button className="camera-round" onClick={()=>file.current?.click()} disabled={busy} aria-label="Choose photo"><ImagePlus size={24}/></button><button className="shutter" onClick={snap} disabled={busy} aria-label="Take photo"><span/></button><span className="camera-round spacer"/></div>}{busy&&<div className="camera-busy" role="status">Opening photo…</div>}</section>
}
