'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,ChevronLeft,Circle,ExternalLink,Globe2,KeyRound,Lightbulb,MapPin,Plus,Sparkles,X} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Candidate,Part,Session,Source,Specimen} from '@/lib/explode/model';
import {categoryColor} from '@/lib/explode/model';
import {apiCall,ConnectionRequired,cropPhoto,detectPhoto,reconstructPhoto} from '@/lib/explode/client';
import {distanceMiles,type LatLng} from '@/lib/explode/geo';
import ModelViewer from './ModelViewer';
import Camera from './Camera';
import Globe from './Globe';
type Screen='camera'|'subjects'|'working'|'explore'|'game';
function Sources({sources,suggestions}:{sources:Source[];suggestions?:string}){return <div className="research-sources">{sources.length>0&&<div className="source-links">{sources.slice(0,5).map((s,i)=><a key={s.url+i} href={s.url} target="_blank" rel="noreferrer">{s.title}<ExternalLink size={12}/></a>)}</div>}{suggestions&&<iframe className="search-suggestions" title="Google Search suggestions" sandbox="allow-popups allow-popups-to-escape-sandbox" srcDoc={suggestions}/>}</div>}
export default function ExplodeApp(){
 const[screen,setScreen]=useState<Screen>('camera'),[specimen,setSpecimen]=useState<Specimen|null>(null),[history,setHistory]=useState<Specimen[]>([]),[amount,setAmount]=useState(0),[hidden,setHidden]=useState<string[]>([]),[part,setPart]=useState<Part|null>(null),[photo,setPhoto]=useState(''),[subject,setSubject]=useState<Candidate|null>(null),[candidates,setCandidates]=useState<Candidate[]>([]),[thumbs,setThumbs]=useState<Record<string,string>>({}),[clarification,setClarification]=useState(''),[error,setError]=useState(''),[phase,setPhase]=useState('Looking closer'),[connecting,setConnecting]=useState(false),[connectOpen,setConnectOpen]=useState(false),[keyInput,setKeyInput]=useState(''),[connectionError,setConnectionError]=useState(''),[hint,setHint]=useState(false),[guess,setGuess]=useState<LatLng|null>(null),[revealing,setRevealing]=useState(false),[revealed,setRevealed]=useState(false);
 const session=useRef<Session>({key:'',model:'',configured:false}),abort=useRef<AbortController|null>(null),pending=useRef<(()=>void)|null>(null),generation=useRef(0);
 const current=useRef({screen,specimen,amount});current.current={screen,specimen,amount};
 useEffect(()=>{const controller=new AbortController();void apiCall<{configured:boolean}>('',session.current,undefined,controller.signal).then(s=>{session.current.configured=s.configured}).catch(()=>{});return()=>{controller.abort();abort.current?.abort()}},[]);
 const newPhoto=useCallback(()=>{generation.current++;abort.current?.abort();pending.current=null;setConnectOpen(false);setPart(null);setPhoto('');setCandidates([]);setClarification('');setError('');setScreen('camera')},[]);
 function ready(task:()=>void){if(session.current.model&&(session.current.configured||session.current.key))task();else{pending.current=task;if(session.current.configured)void connect(true);else{setConnectOpen(true);setConnectionError('')}}}
 async function connect(useServer=false){setConnecting(true);setConnectionError('');const next={...session.current,key:useServer?'':keyInput.trim()};try{const result=await apiCall<{model:string}>('/connect',next,{});session.current={...next,model:result.model};setKeyInput('');setConnectOpen(false);const task=pending.current;pending.current=null;task?.()}catch(e){setConnectionError((e as Error).message);setConnectOpen(true)}finally{setConnecting(false)}}
 async function build(image:string,candidate:Candidate,words:string,parent?:{name:string;part:string;officialName:string}){const gen=++generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setError('');setPart(null);setScreen('working');setPhase(parent?`Inside ${parent.part.toLowerCase()}`:'Finding every little part');try{const result=await reconstructPhoto(session.current,image,candidate,words,controller.signal,parent);if(generation.current!==gen)return;setHistory(h=>parent&&specimen?[...h,specimen]:[]);setSpecimen(result);setAmount(0);setHidden([]);setScreen('explore')}catch(e){if(controller.signal.aborted||generation.current!==gen)return;if(e instanceof ConnectionRequired){session.current.key='';session.current.configured=false;pending.current=()=>void build(image,candidate,words,parent);setConnectOpen(true)}setError((e as Error).message);setScreen(parent&&specimen?'explore':'subjects')}}
 async function analyze(image:string,words=''){const gen=++generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setScreen('working');setPhase('What caught your eye?');setError('');try{const result=await detectPhoto(session.current,image,words,controller.signal);if(generation.current!==gen)return;setCandidates(result.candidates);if(result.candidates.length===1&&result.candidates[0].confidence>=.8){const candidate=result.candidates[0],cropped=await cropPhoto(image,candidate.box);if(generation.current!==gen)return;setPhoto(cropped);setSubject(candidate);void build(cropped,candidate,words);return}const entries=await Promise.all(result.candidates.map(async c=>[c.id,await cropPhoto(image,c.box)] as const));if(generation.current!==gen)return;setThumbs(Object.fromEntries(entries));setScreen('subjects')}catch(e){if(controller.signal.aborted||generation.current!==gen)return;if(e instanceof ConnectionRequired){session.current.key='';session.current.configured=false;pending.current=()=>void analyze(image,words);setConnectOpen(true)}setError((e as Error).message);setScreen('subjects')}}
 const takePhoto=(image:string)=>{setPhoto(image);setSubject(null);setCandidates([]);setThumbs({});setClarification('');setScreen('subjects');ready(()=>void analyze(image))};
 const choose=(c:Candidate)=>{const image=thumbs[c.id]||photo;setPhoto(image);setSubject(c);ready(()=>void build(image,c,clarification))};
 const deeper=(p:Part)=>{if(!specimen||!subject)return;ready(()=>void build(photo,subject,clarification,{name:specimen.name,part:p.name,officialName:p.officialName}))};
 const backModel=()=>{const prev=history.at(-1);if(!prev)return;setSpecimen(prev);setHistory(h=>h.slice(0,-1));setHidden([]);setAmount(1);setPart(null)};
 const play=()=>{setGuess(null);setRevealing(false);setRevealed(false);setHint(false);setScreen('game')};
 const cancel=()=>{generation.current++;abort.current?.abort();setScreen(specimen?'explore':'subjects');setError('')};
 useEffect(()=>{const ctx=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();try{void Promise.resolve(ctx.registerTool({name:'get_exploration',description:'Read the current real-photo reconstruction, its part count, and explosion state. Does not expose photo data or credentials.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({screen:current.current.screen,subject:current.current.specimen?.name??null,parts:current.current.specimen?.parts.length??0,explosion:current.current.amount})},{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort()},[]);
 const categories=specimen?[...new Set(specimen.parts.map(p=>p.category))]:[],visible=specimen?.parts.filter(p=>!hidden.includes(p.category)).length??0;
 const origin=specimen?.origin,centerDistance=guess&&origin?distanceMiles(guess,origin):0,distance=origin?.kind==='region'?Math.max(0,centerDistance-origin.radiusMiles):centerDistance,win=revealed&&distance<=100,score=Math.round(5000*Math.exp(-distance/1600));
 return <main className={'app screen-'+screen}>
 <button className="gemini-key-control" onClick={()=>{pending.current=null;setKeyInput('');setConnectionError('');setConnectOpen(true)}} disabled={connecting||screen==='working'}><KeyRound size={16}/>Gemini key</button>
 {screen==='camera'?<Camera onCapture={takePhoto} onBack={()=>setScreen('explore')} onNew={()=>{setPhoto('');setError('')}} canGoBack={!!specimen}/>:<header className="app-header"><button className="wordmark" onClick={newPhoto} aria-label="Take a new photo">explode me<span>✳</span></button>{screen==='explore'&&<button className="game-link" onClick={play}><Globe2 size={18}/><span>Make it a game!</span><ArrowUpRight size={16}/></button>}{screen==='game'&&<button className="back-object" onClick={()=>setScreen('explore')}><ArrowLeft size={17}/>Back to object</button>}{(screen==='subjects'||screen==='working')&&<button className="icon-button" onClick={screen==='working'?cancel:newPhoto} aria-label="Cancel"><X size={21}/></button>}</header>}
 {screen==='subjects'&&<section className="subject-screen"><div className="subject-title"><h1>{candidates.length?'Pick your subject.':'Something worth a closer look.'}</h1></div>{candidates.length?<div className="candidate-grid">{candidates.map(c=><button className="candidate" key={c.id} onClick={()=>choose(c)}><div className="candidate-image"><img src={thumbs[c.id]||photo} alt={c.label}/></div><span>{c.label}<ArrowUpRight size={17}/></span>{c.confidence<.8&&<small>Possible match</small>}</button>)}</div>:photo&&<div className="captured-photo"><img src={photo} alt="Your photograph"/></div>}{error&&<p className="form-error" role="alert">{error}</p>}<form className="subject-clarification" onSubmit={e=>{e.preventDefault();ready(()=>void analyze(photo,clarification))}}><input aria-label="Clarify the subject" placeholder="Anything we should know?" value={clarification} onChange={e=>setClarification(e.target.value)} maxLength={600}/><button className="primary-button" type="submit">{candidates.length?'Look again':'Explode it'}<ArrowRight size={18}/></button></form></section>}
 {screen==='working'&&<section className="working-screen"><div className="working-animation" aria-hidden>{Array.from({length:9},(_,i)=><i key={i} style={{'--x':i%3-1,'--y':Math.floor(i/3)-1,'--i':i} as React.CSSProperties}/>)}</div><h1 role="status">{phase}<span className="loading-dots">…</span></h1><p>{phase==='What caught your eye?'?'Reading your photograph':'Researching, shaping, separating'}</p><button className="text-button" onClick={cancel}>Cancel</button></section>}
 {screen==='explore'&&specimen&&<section className="explorer"><div className="object-heading">{history.length>0&&<button className="model-back" onClick={backModel}><ChevronLeft size={15}/>{history.at(-1)?.name}</button>}<span className="part-count">{visible.toLocaleString()} parts</span><h1>{specimen.name}<span>.</span></h1></div><div className="object-stage"><ModelViewer specimen={specimen} amount={amount} hidden={hidden} onSelect={setPart}/></div><div className="controls"><div className="filter-row">{categories.map((cat,i)=><label className={'filter '+(hidden.includes(cat)?'off':'')} key={cat}><Checkbox checked={!hidden.includes(cat)} onCheckedChange={v=>setHidden(h=>v?h.filter(x=>x!==cat):[...h,cat])} style={{'--category':categoryColor(i)} as React.CSSProperties}/><span>{cat}</span></label>)}</div><div className="explosion-slider"><button onClick={()=>setAmount(0)} aria-label="Assemble object" className="slider-circle"><Circle size={22} strokeWidth={1.5}/></button><Slider aria-label="Explode into individual parts" min={0} max={1} step={.005} value={[amount]} onValueChange={v=>setAmount(v[0])}/><button onClick={()=>setAmount(1)} aria-label="Lay every part in a grid" className="slider-burst">✳</button></div></div>{error&&<p className="explorer-error" role="alert">{error}</p>}</section>}
 {screen==='game'&&specimen&&origin&&<section className={'game '+(revealed?'answer-shown':'')}><div className="game-title"><span className="game-round">ORIGIN HUNT</span><h1>{specimen.name}<span>?</span></h1></div><div className="earth-stage"><Globe guess={guess} origin={origin} revealing={revealing} onPick={setGuess} onComplete={()=>setRevealed(true)}/>{!revealing&&origin.kind!=='unknown'&&<button className="hint-button" onClick={()=>setHint(v=>!v)}><Lightbulb size={17}/>{hint?'Hide hint':'Need a hint?'}</button>}{hint&&!revealing&&<div className="hint-bubble">{origin.hint}</div>}<a className="earth-credit" href="https://science.nasa.gov/earth/earth-observatory/blue-marble-next-generation/" target="_blank" rel="noreferrer">NASA Earth Observatory</a></div><div className="game-bottom">{origin.kind==='unknown'?<div className="origin-unknown"><h2>A little mystery remains.</h2><p>{origin.explanation||'There is no single verified birthplace for this subject.'}</p><button className="primary-button" onClick={()=>setScreen('explore')}>Keep exploring<ArrowRight size={17}/></button><Sources sources={origin.sources}/></div>:!revealing?<div className="guess-bar"><div className="guess-position"><MapPin size={17}/>{guess?<span>{Math.abs(guess.lat).toFixed(1)}°{guess.lat>=0?'N':'S'} · {Math.abs(guess.lon).toFixed(1)}°{guess.lon>=0?'E':'W'}</span>:<span>Where’s your hunch?</span>}</div><button className="primary-button" disabled={!guess} onClick={()=>{setRevealing(true);setHint(false)}}>That’s my guess<ArrowRight size={17}/></button></div>:!revealed?<div className="flight-status" role="status"><span className="flying-dot"/>Following your hunch…</div>:<div className={'answer-card '+(win?'win':'')}><div className="answer-score"><span>{win?'RIGHT ON THE MAP!':distance<500?'SO CLOSE.':distance<2500?'A GOOD EXPLORATION.':'A WORLD AWAY.'}</span><strong>{score.toLocaleString()}<small> / 5,000</small></strong></div><div className="answer-location"><h2>{origin.place}</h2><span>{Math.round(distance).toLocaleString()} miles {origin.kind==='region'?'from the region':'away'}</span></div><p className="origin-claim">{origin.claim}{origin.kind==='region'?' · Approximate historical region':''}</p><p className="origin-story">{origin.explanation}</p><div className="game-facts"><div className="fact-title"><Sparkles size={17}/><h3>And here’s the good part.</h3></div>{origin.facts.map((fact,i)=><p key={i}>{fact}</p>)}</div><Sources sources={origin.sources} suggestions={specimen.searchSuggestions}/><button className="primary-button wide" onClick={()=>setScreen('explore')}>Keep exploring<ArrowRight size={17}/></button></div>}</div>{win&&<div className="celebration" aria-hidden>{Array.from({length:48},(_,i)=><i key={i} style={{left:(i*73%100)+'%',background:['#275cf2','#f55c3b','#f6bc38','#71ac91'][i%4],animationDelay:(i%11)*.07+'s'}}/>)}</div>}</section>}
 <Dialog open={connectOpen} onOpenChange={open=>{if(!connecting){setConnectOpen(open);if(!open){pending.current=null;setKeyInput('')}}}}><DialogContent className="connect-dialog"><div className="connect-icon"><KeyRound size={23}/></div><DialogTitle>Connect Gemini.</DialogTitle><DialogDescription>Paste a Gemini API key, or replace the key for this tab.</DialogDescription><form onSubmit={e=>{e.preventDefault();void connect()}}><label htmlFor="gemini-key">Gemini API key</label><input id="gemini-key" type="password" autoComplete="off" placeholder="Paste your API key" value={keyInput} onChange={e=>setKeyInput(e.target.value)} required disabled={connecting}/>{connectionError&&<p role="alert" className="form-error">{connectionError}</p>}<button className="primary-button wide" type="submit" disabled={connecting||!keyInput.trim()}>{connecting?'Connecting…':'Connect & continue'}<ArrowRight size={17}/></button>{session.current.configured&&<button type="button" className="text-button server-key-button" disabled={connecting} onClick={()=>void connect(true)}>Use the server key</button>}</form><p className="connection-note">Pasted keys stay in this tab’s memory and override the server key. Photos go to Gemini; usage is billed to the selected key.</p><a className="key-link" href="https://aistudio.google.com/apikey" target="_blank" rel="noreferrer">Get a Gemini key<ExternalLink size={13}/></a></DialogContent></Dialog>
 <Dialog open={!!part} onOpenChange={open=>{if(!open)setPart(null)}}><DialogContent className="part-dialog">{part&&specimen&&<><div className="part-visual"><ModelViewer specimen={specimen} isolated={part}/></div><div className="part-content"><div className="part-category">{part.category}</div><DialogTitle>{part.name}</DialogTitle><DialogDescription className="official-name">{part.officialName}</DialogDescription><section className="part-section"><h3>Made of</h3><p>{part.material}</p></section><section className="part-section"><h3>Its purpose</h3><p>{part.purpose}</p></section><section className="did-you-know"><h3><Sparkles size={17}/>Did you know?</h3>{part.facts.map((fact,i)=><p key={i}>{fact}</p>)}</section>{part.canExplore&&<button className="primary-button wide" onClick={()=>deeper(part)}>Go deeper<Plus size={18}/></button>}<div className="evidence-note">{part.certainty==='observed'?'Visible in your photo':part.certainty==='typical'?'Typical composition':'Estimated composition'} · Illustrative geometry</div><Sources sources={part.sources.length?part.sources:specimen.sources} suggestions={specimen.searchSuggestions}/>{specimen.assumptions.length>0&&<details className="assumptions"><summary>What was estimated</summary><ul>{specimen.assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul></details>}</div></>}</DialogContent></Dialog>
 </main>
}
