'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {LatLng} from '@/lib/explode/geo';
import type {Origin} from '@/lib/explode/model';
export const globeVector=(lat:number,lon:number,r=2.5)=>new T.Vector3(r*Math.cos(lat*Math.PI/180)*Math.cos(lon*Math.PI/180),r*Math.sin(lat*Math.PI/180),-r*Math.cos(lat*Math.PI/180)*Math.sin(lon*Math.PI/180));
function greatCircle(a:T.Vector3,b:T.Vector3,t:number){const theta=Math.acos(T.MathUtils.clamp(a.dot(b),-1,1));if(theta<.00001)return a.clone();if(Math.PI-theta<.001){let axis=new T.Vector3().crossVectors(a,new T.Vector3(0,1,0));if(axis.lengthSq()<.01)axis.set(1,0,0);return a.clone().applyAxisAngle(axis.normalize(),Math.PI*t)}return a.clone().multiplyScalar(Math.sin((1-t)*theta)/Math.sin(theta)).add(b.clone().multiplyScalar(Math.sin(t*theta)/Math.sin(theta))).normalize()}
export default function Globe({guess,origin,revealing,onPick,onComplete}:{guess:LatLng|null;origin:Origin;revealing:boolean;onPick:(p:LatLng)=>void;onComplete:()=>void}){
 const host=useRef<HTMLDivElement>(null),live=useRef({guess,origin,revealing,onPick,onComplete});live.current={guess,origin,revealing,onPick,onComplete};const[error,setError]=useState('');
 useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true})}catch{setError('This browser could not open the globe.');return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.8));renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;el.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(35,1,.01,100);camera.position.copy(globeVector(18,-28,9));const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=2.75;controls.maxDistance=12;controls.rotateSpeed=.55;controls.zoomSpeed=.9;scene.add(new T.AmbientLight('#ffffff',2));const sun=new T.DirectionalLight('#ffffff',2.1);sun.position.set(6,8,8);scene.add(sun);
 const mat=new T.MeshStandardMaterial({color:'#dbe2ec',roughness:.93});const globe=new T.Mesh(new T.SphereGeometry(2.5,144,96),mat);scene.add(globe);const textures:T.Texture[]=[];let alive=true;const loader=new T.TextureLoader();loader.load('/textures/earth-day.jpg',t=>{if(!alive){t.dispose();return}t.colorSpace=T.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();textures.push(t);mat.map=t;mat.color.set('#ffffff');mat.needsUpdate=true},undefined,()=>setError('Earth imagery could not load. Please reopen the game.'));loader.load('/textures/earth-bump.jpg',t=>{if(!alive){t.dispose();return}textures.push(t);mat.bumpMap=t;mat.bumpScale=.025;mat.needsUpdate=true});
 const atmosphere=new T.Mesh(new T.SphereGeometry(2.54,80,64),new T.ShaderMaterial({transparent:true,side:T.BackSide,depthWrite:false,uniforms:{glow:{value:new T.Color('#689ddb')}},vertexShader:'varying vec3 vN; varying vec3 vP; void main(){vN=normalize(normalMatrix*normal); vec4 p=modelViewMatrix*vec4(position,1.0); vP=p.xyz; gl_Position=projectionMatrix*p;}',fragmentShader:'varying vec3 vN; varying vec3 vP; uniform vec3 glow; void main(){float a=pow(1.0-abs(dot(normalize(vN),normalize(-vP))),3.5)*0.42; gl_FragColor=vec4(glow,a);}'}));scene.add(atmosphere);
 const borders=new T.Group();scene.add(borders);const labels:T.Sprite[]=[];const abort=new AbortController();fetch('/world.json',{signal:abort.signal}).then(r=>r.json()).then(raw=>{if(!alive)return;const data=raw as {features:{properties:{name:string};geometry:{type:string;coordinates:number[][][]|number[][][][]}}[]};const positions:number[]=[];for(const feature of data.features){const polys=(feature.geometry.type==='Polygon'?[feature.geometry.coordinates]:feature.geometry.coordinates) as number[][][][];let biggest:number[][]=[],area=0;for(const poly of polys){const ring=poly[0];let a=0;for(let i=0;i<ring.length-1;i++){const p=globeVector(ring[i][1],ring[i][0],2.505),q=globeVector(ring[i+1][1],ring[i+1][0],2.505);if(p.distanceTo(q)<.8)positions.push(...p.toArray(),...q.toArray());a+=ring[i][0]*ring[i+1][1]-ring[i+1][0]*ring[i][1]}if(Math.abs(a)>area){area=Math.abs(a);biggest=ring}}
 if(area>5&&biggest.length){const center=new T.Vector3();biggest.forEach(p=>center.add(globeVector(p[1],p[0],1)));center.normalize();const canvas=document.createElement('canvas');canvas.width=512;canvas.height=64;const ctx=canvas.getContext('2d')!;ctx.textAlign='center';ctx.font='500 24px Arial';ctx.strokeStyle='rgba(16,32,43,.8)';ctx.lineWidth=3;ctx.strokeText(feature.properties.name.toUpperCase(),256,40);ctx.fillStyle='#f6fbff';ctx.fillText(feature.properties.name.toUpperCase(),256,40);const tex=new T.CanvasTexture(canvas);textures.push(tex);const label=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthTest:true,depthWrite:false}));label.position.copy(center.multiplyScalar(2.525));label.scale.set(.72,.09,1);label.userData.area=area;scene.add(label);labels.push(label)}}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));borders.add(new T.LineSegments(geo,new T.LineBasicMaterial({color:'#dce5e8',transparent:true,opacity:.26})));}).catch(()=>{});
 const markers=new T.Group();scene.add(markers);function marker(pos:LatLng,color:string){const point=globeVector(pos.lat,pos.lon,2.54),g=new T.Group();const dot=new T.Mesh(new T.SphereGeometry(.035,20,14),new T.MeshBasicMaterial({color}));g.add(dot);const ring=new T.Mesh(new T.TorusGeometry(.068,.009,8,40),new T.MeshBasicMaterial({color:'#ffffff'}));ring.lookAt(point);g.add(ring);g.position.copy(point);markers.add(g);return g}
 function clear(){markers.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){o.geometry.dispose();(o.material as T.Material).dispose()}});markers.clear()}
 const ray=new T.Raycaster(),pointer=new T.Vector2();let start=[0,0],move=0,multi=false;const pointers=new Set<number>();renderer.domElement.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size===1){start=[e.clientX,e.clientY];move=0;multi=false}else multi=true});renderer.domElement.addEventListener('pointermove',e=>{if(pointers.size)move=Math.max(move,Math.hypot(e.clientX-start[0],e.clientY-start[1]))});renderer.domElement.addEventListener('pointercancel',e=>pointers.delete(e.pointerId));renderer.domElement.addEventListener('pointerup',e=>{const can=pointers.has(e.pointerId)&&!multi&&move<7;pointers.delete(e.pointerId);if(!can||live.current.revealing||live.current.origin.kind==='unknown')return;const r=el.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(globe)[0];if(hit){const p=hit.point.normalize();live.current.onPick({lat:Math.asin(p.y)*180/Math.PI,lon:Math.atan2(-p.z,p.x)*180/Math.PI})}});
 renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Earth. Arrow keys move the globe, plus and minus zoom, Enter places a pin.');renderer.domElement.addEventListener('keydown',e=>{if(live.current.revealing)return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','Enter'].includes(e.key))e.preventDefault();const p=camera.position.clone().normalize(),lat=Math.asin(p.y)*180/Math.PI,lon=Math.atan2(-p.z,p.x)*180/Math.PI,d=camera.position.length();if(e.key==='Enter'&&live.current.origin.kind!=='unknown')live.current.onPick({lat,lon});else if(e.key==='+')camera.position.multiplyScalar(.9);else if(e.key==='-')camera.position.multiplyScalar(1.1);else if(e.key.startsWith('Arrow'))camera.position.copy(globeVector(Math.max(-85,Math.min(85,lat+(e.key==='ArrowUp'?4:e.key==='ArrowDown'?-4:0))),lon+(e.key==='ArrowLeft'?-4:e.key==='ArrowRight'?4:0),d))});
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0,lastGuess='',flightStart=0,complete=false,moving:T.Group|undefined,path:T.Line|undefined,startV=new T.Vector3(),endV=new T.Vector3(),startCamera=new T.Vector3();
 const animate=(now:number)=>{frame=requestAnimationFrame(animate);const st=live.current;if(!st.revealing){const sig=JSON.stringify(st.guess);if(sig!==lastGuess){lastGuess=sig;clear();if(st.guess)marker(st.guess,'#f14e45')}}else if(!flightStart&&st.guess){flightStart=now;startV=globeVector(st.guess.lat,st.guess.lon,1);endV=globeVector(st.origin.lat,st.origin.lon,1);startCamera.copy(camera.position);clear();marker(st.guess,'#e2b6b0');moving=marker(st.guess,'#f04e45');const pts=Array.from({length:241},(_,i)=>greatCircle(startV,endV,i/240).multiplyScalar(2.545+Math.sin(Math.PI*i/240)*.13));path=new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineBasicMaterial({color:'#f4554c',transparent:true,opacity:.95}));path.geometry.setDrawRange(0,0);markers.add(path);controls.enabled=false;}
 if(flightStart&&!complete&&moving&&path){const time=(now-flightStart)/7800,t=T.MathUtils.clamp(time,0,1),ease=t*t*(3-2*t),direction=greatCircle(startV,endV,ease);moving.position.copy(direction.clone().multiplyScalar(2.545+Math.sin(Math.PI*ease)*.13));moving.children[1].lookAt(direction);path.geometry.setDrawRange(0,Math.max(2,Math.ceil(ease*240)+1));const destination=direction.clone().multiplyScalar(7.5);camera.position.lerpVectors(startCamera,destination,T.MathUtils.smoothstep(t,0,.3));camera.lookAt(0,0,0);if(time>=1){complete=true;controls.enabled=true;marker(st.origin,'#629b83');if(st.origin.kind==='region'&&st.origin.radiusMiles>0){const angular=Math.min(Math.PI/2,st.origin.radiusMiles/3958.7613),normal=endV.clone(),a=new T.Vector3().crossVectors(normal,new T.Vector3(0,1,0));if(a.lengthSq()<.001)a.set(1,0,0);a.normalize();const b=new T.Vector3().crossVectors(normal,a);const ringPoints=Array.from({length:161},(_,i)=>normal.clone().multiplyScalar(Math.cos(angular)).addScaledVector(a,Math.sin(angular)*Math.cos(i/160*Math.PI*2)).addScaledVector(b,Math.sin(angular)*Math.sin(i/160*Math.PI*2)).multiplyScalar(2.535));markers.add(new T.Line(new T.BufferGeometry().setFromPoints(ringPoints),new T.LineBasicMaterial({color:'#dfeead',transparent:true,opacity:.85})));}st.onComplete()}}
 controls.update();const cameraDirection=camera.position.clone().normalize(),zoom=camera.position.length();for(const label of labels){label.visible=zoom<6.8&&label.position.clone().normalize().dot(cameraDirection)>.45&&((label.userData.area as number)>40||zoom<4.4);(label.material as T.SpriteMaterial).opacity=T.MathUtils.clamp((6.8-zoom)/1.3,0,1)}renderer.render(scene,camera)};frame=requestAnimationFrame(animate);return()=>{alive=false;abort.abort();cancelAnimationFrame(frame);observer.disconnect();controls.dispose();clear();scene.traverse(o=>{if(o instanceof T.Mesh||o instanceof T.Line){o.geometry.dispose();(o.material as T.Material).dispose()}else if(o instanceof T.Sprite){o.material.dispose()}});textures.forEach(t=>t.dispose());renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};
 },[origin.title]);
 return <div className="globe-host" ref={host}>{error&&<p className="canvas-error">{error}</p>}</div>
}
