'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createPart,disposeObject} from '@/lib/explode/geometry';
import {gridSlots} from '@/lib/explode/assembly';
import type {Part,Specimen} from '@/lib/explode/model';
export default function ModelViewer({specimen,amount=0,hidden=[],onSelect,isolated}:{specimen:Specimen;amount?:number;hidden?:string[];onSelect?:(p:Part)=>void;isolated?:Part}){
 const host=useRef<HTMLDivElement>(null),live=useRef({amount,hidden,onSelect});live.current={amount,hidden,onSelect};const[error,setError]=useState('');
 useEffect(()=>{if(!host.current)return;setError('');const el=host.current;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'})}catch{setError('Open this in Safari or Chrome to view it in 3D.');return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;el.appendChild(renderer.domElement);
 const scene=new T.Scene(),camera=new T.OrthographicCamera(-3,3,3,-3,.01,200);camera.position.set(isolated?5:6,isolated?2.5:3.5,9);camera.lookAt(0,0,0);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.09;controls.minZoom=.4;controls.maxZoom=50;controls.touches.ONE=T.TOUCH.ROTATE;controls.touches.TWO=T.TOUCH.DOLLY_PAN;controls.zoomToCursor=true;
 scene.add(new T.HemisphereLight('#fffdf8','#a6b2ca',2.15));const key=new T.DirectionalLight('#fff5e5',3.7);key.position.set(3,8,6);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.bias=-.001;scene.add(key);const rim=new T.DirectionalLight('#ddeaff',2);rim.position.set(-5,2,-4);scene.add(rim);
 const root=new T.Group();scene.add(root);const parts=isolated?[isolated]:specimen.parts;const complete=new T.Box3();const items=parts.map(part=>{const model=createPart(part),bounds=new T.Box3().setFromObject(model),center=bounds.getCenter(new T.Vector3()),radius=bounds.getBoundingSphere(new T.Sphere()).radius;model.position.sub(center);const group=new T.Group();group.add(model);root.add(group);const assembled=new T.Vector3(...part.pos).add(center);complete.union(bounds.clone().translate(new T.Vector3(...part.pos)));return {part,model,group,assembled,radius:Math.max(radius,.001)}});
 const overallCenter=complete.getCenter(new T.Vector3()),size=complete.getSize(new T.Vector3()),norm=3.9/Math.max(size.x,size.y,size.z,.001);const initialScale=isolated?1.8/items[0].radius:norm;
 const ray=new T.Raycaster(),mouse=new T.Vector2(),right=new T.Vector3(),up=new T.Vector3(),target=new T.Vector3();const active=new Set<number>();let start={x:0,y:0},moved=0,multi=false,keyboardPart=0;
 const hit=(e:PointerEvent)=>{const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(mouse,camera);return ray.intersectObjects(items.filter(x=>x.group.visible).map(x=>x.group),true)[0]?.object.userData.part as Part|undefined};
 const down=(e:PointerEvent)=>{active.add(e.pointerId);if(active.size===1){start={x:e.clientX,y:e.clientY};moved=0;multi=false}else multi=true};
 const move=(e:PointerEvent)=>{if(active.size)moved=Math.max(moved,Math.hypot(e.clientX-start.x,e.clientY-start.y));else if(e.pointerType==='mouse')renderer.domElement.style.cursor=!isolated&&hit(e)?'pointer':'grab'};
 const end=(e:PointerEvent)=>{const choose=active.has(e.pointerId)&&!multi&&moved<7;active.delete(e.pointerId);if(choose&&!isolated){const p=hit(e);if(p)live.current.onSelect?.(p)}};
 renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',end);renderer.domElement.addEventListener('pointercancel',e=>active.delete(e.pointerId));renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('role','application');renderer.domElement.setAttribute('aria-label',isolated?`${isolated.name}, interactive three dimensional model`:`${specimen.name}. Use left and right arrow keys to choose a component, then Enter to inspect.`);
 renderer.domElement.addEventListener('keydown',e=>{if(isolated)return;const visible=parts.filter(p=>!live.current.hidden.includes(p.category));if(!visible.length)return;if(['ArrowLeft','ArrowRight','Enter'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')keyboardPart=(keyboardPart+visible.length-1)%visible.length;if(e.key==='ArrowRight')keyboardPart=(keyboardPart+1)%visible.length;if(e.key==='Enter')live.current.onSelect?.(visible[keyboardPart%visible.length]);renderer.domElement.setAttribute('aria-label',`${visible[keyboardPart%visible.length].name}. Press Enter to inspect.`)});
 let aspect=1;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;aspect=w/h;camera.left=-3*aspect;camera.right=3*aspect;camera.top=3;camera.bottom=-3;camera.updateProjectionMatrix();renderer.setSize(w,h)};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0,current=live.current.amount,slots=gridSlots(parts.length),lastHidden='';
 const animate=()=>{frame=requestAnimationFrame(animate);const st=live.current;current+=(st.amount-current)*.11;if(Math.abs(st.amount-current)<.0001)current=st.amount;controls.update();right.setFromMatrixColumn(camera.matrixWorld,0).normalize();up.setFromMatrixColumn(camera.matrixWorld,1).normalize();const visible=items.filter(x=>!st.hidden.includes(x.part.category)),signature=st.hidden.join('|');if(signature!==lastHidden){lastHidden=signature;slots=gridSlots(visible.length)}const n=Math.ceil(Math.sqrt(Math.max(1,visible.length))),cell=4.75*Math.min(1,aspect)/n;let index=0;
 for(const item of items){item.group.visible=!st.hidden.includes(item.part.category);if(!item.group.visible)continue;if(isolated){item.group.position.set(0,0,0);item.group.scale.setScalar(initialScale);continue}const slot=slots[index]??gridSlots(visible.length)[index];const lag=(index%7)*.006,linear=T.MathUtils.clamp((current-lag)/(1-lag),0,1),t=linear*linear*(3-2*linear);target.copy(right).multiplyScalar(slot.x*cell).addScaledVector(up,slot.y*cell);const startPos=item.assembled.clone().sub(overallCenter).multiplyScalar(norm);item.group.position.copy(startPos.lerp(target,t));item.group.position.addScaledVector(up,Math.sin(Math.PI*t)*Math.sin(index*2.4)*.17);item.group.scale.setScalar(T.MathUtils.lerp(norm,cell*.405/item.radius,t));index++;}
 renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(frame);observer.disconnect();controls.dispose();disposeObject(scene);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove()};
 },[specimen.id,isolated?.id]);
 return <div className="model-viewer" ref={host}>{error&&<p className="canvas-error">{error}</p>}</div>
}
